
import Footer from './components/Footer/Footer'
import Navbar from './components/Navbar/Navbar'
import './globals.css'



export const metadata = {
  title: 'mailflowai',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='pt-[10vh]'>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
